/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["Inter", "Segoe UI", "system-ui", "sans-serif"],
        heading: ["Hanken Grotesk", "Inter", "Segoe UI", "system-ui", "sans-serif"],
        "body-md": ["Inter"],
        "headline-sm": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Hanken Grotesk"],
        "body-sm": ["Inter"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
      },
      colors: {
        error: "#ba1a1a",
        outline: "#767680",
        "surface-container-low": "#f5f3f0",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#001d35",
        "surface-bright": "#fbf9f6",
        "on-background": "#1b1c1a",
        "on-secondary-fixed-variant": "#00497b",
        "secondary-fixed": "#d1e4ff",
        "tertiary-fixed-dim": "#ffb95f",
        "primary-fixed": "#dbe1ff",
        "on-tertiary-fixed": "#2a1700",
        background: "#fbf9f6",
        "primary-fixed-dim": "#b7c5f8",
        "surface-container-high": "#eae8e5",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffddb8",
        "on-primary-fixed-variant": "#384571",
        "inverse-surface": "#30312f",
        "surface-tint": "#4f5d8a",
        "inverse-on-surface": "#f2f0ed",
        surface: "#fbf9f6",
        "status-review": "#1e9af7",
        "surface-container": "#efeeeb",
        "secondary-fixed-dim": "#9dcaff",
        "status-hired": "#10b981",
        "on-surface-variant": "#45464f",
        "on-surface": "#1b1c1a",
        "on-tertiary": "#ffffff",
        secondary: "#0062a2",
        "secondary-container": "#2ba0fd",
        "surface-warm": "#fcfaf7",
        "on-primary-container": "#7886b6",
        "status-new": "#64748b",
        "status-contacted": "#f59e0b",
        "on-tertiary-container": "#bd7800",
        tertiary: "#0f0600",
        "on-secondary": "#ffffff",
        "tertiary-container": "#301b00",
        "on-error-container": "#93000a",
        "surface-variant": "#e4e2df",
        "on-tertiary-fixed-variant": "#653e00",
        "primary-container": "#0e1d47",
        "surface-dim": "#dbdad7",
        "on-secondary-container": "#00355b",
        "outline-variant": "#c6c6d0",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "inverse-primary": "#b7c5f8",
        "status-rejected": "#ef4444",
        primary: "#000621",
        "surface-card": "#ffffff",
        "surface-container-highest": "#e4e2df",
        "on-primary-fixed": "#091843",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-width": "260px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        "container-padding": "32px",
        base: "4px",
        xl: "32px",
        "grid-gutter": "24px",
        lg: "24px",
      },
      boxShadow: {
        card: "0px 4px 12px rgba(14, 29, 71, 0.05)",
        "card-lg": "0px 8px 24px rgba(14, 29, 71, 0.12)",
      },
      transitionDuration: {
        150: "150ms",
        200: "200ms",
        250: "250ms",
      },
      keyframes: {
        fadeIn: { from: { opacity: 0 }, to: { opacity: 1 } },
        slideUp: { from: { opacity: 0, transform: "translateY(16px)" }, to: { opacity: 1, transform: "translateY(0)" } },
        scaleIn: { from: { opacity: 0, transform: "scale(0.96)" }, to: { opacity: 1, transform: "scale(1)" } },
      },
      animation: {
        "fade-in": "fadeIn 200ms ease-out",
        "slide-up": "slideUp 250ms ease-out",
        "scale-in": "scaleIn 150ms ease-out",
      },
    },
  },
  plugins: [],
};
